stages:
  - build
  - trigger

default:
  interruptible: true

workflow:
  rules:
    - if: $CI_EXTERNAL_PULL_REQUEST_IID


trigger_internal_ci:
  stage: build
  image: node
  tags: 
    - docker-prod
  variables:
    DOWNSTREAM_PROJECT_ID: $DOWNSTREAM_PROJECT_ID
    DOWNSTREAM_PROJECT_NAME: $DOWNSTREAM_PROJECT_NAME
  script:
    - echo $CI_EXTERNAL_PULL_REQUEST_SOURCE_BRANCH_NAME
    - export TRIGGER_BRANCH=$CI_EXTERNAL_PULL_REQUEST_SOURCE_BRANCH_NAME
    - echo $DOWNSTREAM_PROJECT_ID
    - 'curl -v --fail --request POST --header "PRIVATE-TOKEN: $SVC_HLS_RENDER_API" "https://main.gitlab.in.here.com/api/v4/projects/12500/repository/branches?branch=$CI_EXTERNAL_PULL_REQUEST_SOURCE_BRANCH_NAME&ref=master"'
    - scripts/generate-config.sh
  artifacts:
     paths:
      - generated-config.yml


bridge_for_bridge:
  stage: trigger
  trigger:
    include:
      - artifact: generated-config.yml
        job: trigger_internal_ci
    strategy: depend
