var files = {
    "verity": {
        "dist/verity_camera_free.html": "/home/harald/here/vsdk/mapsdk/@here/verity-examples/src/verity_camera_free.ts",
        "dist/verity_datasource_async.html": "/home/harald/here/vsdk/mapsdk/@here/verity-examples/src/verity_datasource_async.ts",
        "dist/verity_datasource_hello.html": "/home/harald/here/vsdk/mapsdk/@here/verity-examples/src/verity_datasource_hello.ts",
        "dist/verity_datasource_mocked.html": "/home/harald/here/vsdk/mapsdk/@here/verity-examples/src/verity_datasource_mocked.ts",
        "dist/verity_datasource_places.html": "/home/harald/here/vsdk/mapsdk/@here/verity-examples/src/verity_datasource_places.ts",
        "dist/verity_datasource_roads.html": "/home/harald/here/vsdk/mapsdk/@here/verity-examples/src/verity_datasource_roads.ts",
        "dist/verity_datasource_route_highPrecision.html": "/home/harald/here/vsdk/mapsdk/@here/verity-examples/src/verity_datasource_route_highPrecision.ts",
        "dist/verity_datasource_route_solid.html": "/home/harald/here/vsdk/mapsdk/@here/verity-examples/src/verity_datasource_route_solid.ts",
        "dist/verity_datasource_route.html": "/home/harald/here/vsdk/mapsdk/@here/verity-examples/src/verity_datasource_route.ts",
        "dist/verity_datasource_simple.html": "/home/harald/here/vsdk/mapsdk/@here/verity-examples/src/verity_datasource_simple.ts",
        "dist/verity_datasource_terrain.html": "/home/harald/here/vsdk/mapsdk/@here/verity-examples/src/verity_datasource_terrain.ts",
        "dist/verity_datasource_webtile.html": "/home/harald/here/vsdk/mapsdk/@here/verity-examples/src/verity_datasource_webtile.ts",
        "dist/verity_drive.html": "/home/harald/here/vsdk/mapsdk/@here/verity-examples/src/verity_drive.ts",
        "dist/verity_earthcore_3d_cities.html": "/home/harald/here/vsdk/mapsdk/@here/verity-examples/src/verity_earthcore_3d_cities.ts",
        "dist/verity_fonts_textwall_path.html": "/home/harald/here/vsdk/mapsdk/@here/verity-examples/src/verity_fonts_textwall_path.ts",
        "dist/verity_fonts_textwall.html": "/home/harald/here/vsdk/mapsdk/@here/verity-examples/src/verity_fonts_textwall.ts",
        "dist/verity_fonts.html": "/home/harald/here/vsdk/mapsdk/@here/verity-examples/src/verity_fonts.ts",
        "dist/verity_hello_onethread.html": "/home/harald/here/vsdk/mapsdk/@here/verity-examples/src/verity_hello_onethread.ts",
        "dist/verity_hello.html": "/home/harald/here/vsdk/mapsdk/@here/verity-examples/src/verity_hello.ts",
        "dist/verity_hype_gettile.html": "/home/harald/here/vsdk/mapsdk/@here/verity-examples/src/verity_hype_gettile.ts",
        "dist/verity_mapview_languages.html": "/home/harald/here/vsdk/mapsdk/@here/verity-examples/src/verity_mapview_languages.ts",
        "dist/verity_multiview_syncview.html": "/home/harald/here/vsdk/mapsdk/@here/verity-examples/src/verity_multiview_syncview.ts",
        "dist/verity_multiview_tripleView.html": "/home/harald/here/vsdk/mapsdk/@here/verity-examples/src/verity_multiview_tripleView.ts",
        "dist/verity_omv_dataproviders.html": "/home/harald/here/vsdk/mapsdk/@here/verity-examples/src/verity_omv_dataproviders.ts",
        "dist/verity_performance_animation.html": "/home/harald/here/vsdk/mapsdk/@here/verity-examples/src/verity_performance_animation.ts",
        "dist/verity_performance_antialias.html": "/home/harald/here/vsdk/mapsdk/@here/verity-examples/src/verity_performance_antialias.ts",
        "dist/verity_react-native-web.html": "/home/harald/here/vsdk/mapsdk/@here/verity-examples/src/verity_react-native-web.tsx",
        "dist/verity_scrapbox_lines_screenspace.html": "/home/harald/here/vsdk/mapsdk/@here/verity-examples/src/verity_scrapbox_lines_screenspace.ts",
        "dist/verity_themes.html": "/home/harald/here/vsdk/mapsdk/@here/verity-examples/src/verity_themes.ts",
        "dist/verity_xyz_show_space.html": "/home/harald/here/vsdk/mapsdk/@here/verity-examples/src/verity_xyz_show_space.ts",
        "dist/verity_hello_map-bundle.html": "/home/harald/here/vsdk/mapsdk/@here/verity-examples/src/verity_hello_map-bundle.html"
    }
}
