#!/usr/bin/env node

const handler = require("serve-handler");
const http = require("http");

const options = {
    "cleanUrls": false,
    "public": __dirname
};

const server = http.createServer((request, response) => {
    if (request.url === "/") {
        request.url = "/index.html";
    }
    return handler(request, response, options);
});

server.listen(5000, () => {
    console.log("Running at http://localhost:5000");
});
