/*
 * Copyright (C) 2017-2018 HERE Europe B.V.
 * Licensed under Apache 2.0, see full license in LICENSE
 * SPDX-License-Identifier: Apache-2.0
 */

import {
    createMaterial,
    DecodedTile,
    ExtrudedPolygonTechnique,
    FillTechnique,
    Geometry,
    GeometryType,
    getArrayConstructor,
    getAttributeValue,
    getBufferAttribute,
    getObjectConstructor,
    getPropertyValue,
    isExtrudedPolygonTechnique,
    isStandardTechnique,
    SolidLineTechnique,
    StandardExtrudedLineTechnique,
    Technique,
    TextPathGeometry
} from "@here/harp-datasource-protocol";
import { GeoBox, Projection, TileKey } from "@here/harp-geoutils";
import {
    DashedLineMaterial,
    EdgeMaterial,
    EdgeMaterialParameters,
    FadingFeature,
    SolidLineMaterial
} from "@here/harp-materials";
import {
    TextHorizontalAlignment,
    TextHorizontalAlignmentStrings,
    TextVerticalAlignment,
    TextVerticalAlignmentStrings
} from "@here/harp-text-renderer";
import {
    CachedResource,
    getOptionValue,
    GroupedPriorityList,
    PerformanceTimer
} from "@here/harp-utils";
import * as THREE from "three";

import { ColorCache } from "./ColorCache";
import { DataSource } from "./DataSource";
import {
    applyDepthBasedPolygonOffset,
    createDepthPrePassMesh,
    DEFAULT_DEPTH_BASED_POLYGON_OFFSET_MULTIPLIER,
    isRenderDepthPrePassEnabled
} from "./DepthPrePass";
import { MapView } from "./MapView";
import { TextElement } from "./text/TextElement";
import { DEFAULT_TEXT_DISTANCE_SCALE } from "./text/TextElementsRenderer";
import { MapViewUtils } from "./Utils";

export type TileObject = THREE.Object3D & {
    /**
     * Distance of this object from the [[Tile]]'s center.
     */
    displacement?: THREE.Vector3;
};

interface DisposableObject {
    geometry?: THREE.BufferGeometry | THREE.Geometry;
    material?: THREE.Material[] | THREE.Material;
}

/**
 * An interface for optional feature data that is saved in a `THREE.Object3D`'s `userData`
 * property.
 */
export interface TileFeatureData {
    /**
     * The original type of geometry.
     */
    geometryType?: GeometryType;

    /**
     * An optional array of feature IDs.
     */
    ids?: Array<number | undefined>;

    /**
     * An optional array of indices into geometry where the feature starts. The lists of IDs
     * and starting indices (starts) must have the same size.
     */
    starts?: number[];

    /**
     * An optional object containing properties defined by the developer. It has the same size as
     * the list of IDs and the starting indices (starts).
     */
    objInfos?: Array<{} | undefined>;
}

/**
 * Contains data that describes the road on a `tile`. The `RoadIntersectionData` is generated by
 * the [[RoadPicker]] class.
 *
 * @see [[RoadPicker]]
 */
export interface RoadIntersectionData {
    /**
     * Optional array of feature IDs.
     */
    ids: Array<number | undefined>;

    /**
     * An array of indices into the technique catalog. The lists of `techniqueIndex` and `starts`
     * have the same size.
     */
    techniqueIndex: number[];

    /**
     * An array of the indices into geometry where the feature starts. The lists of IDs and
     * starting indices (starts) have the same size.
     */
    starts: number[];

    /**
     * An array of widths of the roads. The lists of IDs and widths have the same size.
     */
    widths: number[];

    /**
     * An array of 2D numbers that make up the road geometry.
     */
    positions: number[];

    /**
     * A catalog of [[Technique]]s for road lines. Allows to reconstruct the visual appearance of
     * the identified line.
     */
    techniques: Technique[];
    /**
     * An optional object that contains properties defined by the developer. This object has the
     * same size as the list of IDs and the starts.
     */
    objInfos?: Array<{} | undefined>;
}

/**
 * Missing Typedoc
 */
export enum TileLoaderState {
    Initialized,
    Loading,
    Loaded,
    Decoding,
    Ready,
    Canceled,
    Failed,
    Disposed
}

export interface ITileLoader {
    state: TileLoaderState;
    payload?: ArrayBufferLike | {};
    decodedTile?: DecodedTile;

    loadAndDecode(): Promise<TileLoaderState>;
    waitSettled(): Promise<TileLoaderState>;

    cancel(): void;
    dispose(): void;

    isFinished(): boolean;
}

/**
 * An object that contains information about resources used by a tile.
 */
export interface TileResourceUsageInfo {
    /**
     * The estimated memory usage, in bytes.
     */
    estimatedMemoryUsage: number;
    /**
     * The amount of vertices used by a tile.
     */
    numVertices: number;
    /**
     * The amount of colors used by a tile.
     */
    numColors: number;
    /**
     * The amount of objects used by a tile.
     */
    numObjects: number;
    /**
     * The amount of geometries used by a tile.
     */
    numGeometries: number;
    /**
     * The amount of materials used by a tile.
     */
    numMaterials: number;
}

/**
 * The SORT_WEIGHT_SEQUENCE and SORT_WEIGHT_PATH_LENGTH constants control how the priority
 * of the labels are computed based on two factors:
 * - The occurrence in the set of labels, from first to last
 * - The length of the label strings
 * Consequently, this priority is slightly modified while generating [[TextElement]]s from the
 * [[DecodedTile]], to get a meaningful priority and stable results.
 */

/**
 * The amount of influence the original position has on rendering the [[TextElement]]. Sorts
 * both point labels with path lengths (such as roads) and those without path lengths.
 */
const SORT_WEIGHT_SEQUENCE = 0.1;

/**
 * Gives [[TextElement]]s with longer paths a higher priority since they are easier to place,
 * so they are more likely to be placed. If resource is limited, less labels are checked.
 */
const SORT_WEIGHT_PATH_LENGTH = 1.0 - SORT_WEIGHT_SEQUENCE;

/**
 * A factor used for memory estimation.
 */
const MEMORY_UNDERESTIMATION_FACTOR = 2;

/**
 * Parameters that control fading.
 */
interface FadingParameters {
    fadeNear?: number;
    fadeFar?: number;
}

/**
 * Parameters that control fading for extruded buildings with fading edges.
 */
interface PolygonFadingParameters extends FadingParameters {
    color?: string | number;
    colorMix?: number;
    lineFadeNear?: number;
    lineFadeFar?: number;
}

/**
 * The class that holds the tiled data for a [[DataSource]].
 */
export class Tile implements CachedResource {
    /**
     * A list of the THREE.js objects stored in this `Tile`.
     */
    readonly objects: TileObject[] = [];

    /**
     * The optional list of HERE TileKeys of tiles with geometries that cross
     * the boundaries of this `Tile`.
     */
    readonly dependencies: string[] = new Array<string>();

    /**
     * The bounding box of this `Tile` in geocoordinates.
     */
    readonly geoBox: GeoBox;

    /**
     * The bounding box of this `Tile` in world coordinates.
     */
    readonly boundingBox: THREE.Box3 = new THREE.Box3();

    /**
     * The center of this `Tile` in world coordinates.
     */
    readonly center: THREE.Vector3 = new THREE.Vector3();

    /**
     * A record of road data that cannot be intersected with THREE.JS, because the geometry is
     * created in the vertex shader.
     */
    roadIntersectionData?: RoadIntersectionData;

    private m_disposed: boolean = false;

    private m_forceHasGeometry: boolean | undefined = undefined;

    private m_tileLoader?: ITileLoader;
    private m_decodedTile?: DecodedTile;

    /**
     * Prepared text geometries optimized for display.
     */
    private m_preparedTextPaths: TextPathGeometry[] = new Array();

    // Used for [[TextElement]]s which the developer defines.
    private readonly m_userTextElements: TextElement[] = [];

    // Used for [[TextElement]]s that are stored in the data, and that are placed explicitly,
    // fading in and out.
    private readonly m_textElementGroups: GroupedPriorityList<
        TextElement
    > = new GroupedPriorityList<TextElement>();

    // All visible [[TextElement]]s.
    private readonly m_placedTextElements: GroupedPriorityList<
        TextElement
    > = new GroupedPriorityList<TextElement>();
    private m_numVertices: number = 0;

    private m_memoryUsage: number | undefined = undefined;

    // If `true`, the text content of the [[Tile]] changed.
    private m_textElementsChanged: boolean = false;

    /**
     * Creates a new `Tile`.
     *
     * @param dataSource The [[DataSource]] that created this `Tile`.
     * @param tileKey The unique identifier for this `Tile`.
     */
    constructor(readonly dataSource: DataSource, readonly tileKey: TileKey) {
        this.geoBox = this.dataSource.getTilingScheme().getGeoBox(this.tileKey);
        this.projection.projectBox(this.geoBox, this.boundingBox);
        this.boundingBox.getCenter(this.center);
    }

    /**
     * The [[Projection]] currently used by the [[MapView]].
     */
    get projection(): Projection {
        return this.dataSource.projection;
    }

    /**
     * The [[MapView]] this `Tile` belongs to.
     */
    get mapView(): MapView {
        return this.dataSource.mapView;
    }

    /**
     * Get the currently visible [[TextElement]]s of this `Tile`. This list is continuously
     * modified, and is not designed to be used to store developer-defined [[TextElements]].
     */
    get placedTextElements(): GroupedPriorityList<TextElement> {
        return this.m_placedTextElements;
    }

    /*
     * The size of this Tile in system memory.
     */
    get memoryUsage(): number {
        if (this.m_memoryUsage !== undefined) {
            return this.m_memoryUsage;
        }
        let numBytesUsed = 0;
        if (this.decodedTile !== undefined) {
            numBytesUsed += MapViewUtils.estimateObjectSize(this.decodedTile);
        }
        numBytesUsed += MapViewUtils.estimateObjectSize(this.textElementGroups);
        numBytesUsed += MapViewUtils.estimateObjectSize(this.objects);
        numBytesUsed += MapViewUtils.estimateObjectSize(this.preparedTextPaths);
        if (this.roadIntersectionData) {
            numBytesUsed += MapViewUtils.estimateObjectSize(this.roadIntersectionData);
        }
        this.m_memoryUsage = numBytesUsed;
        return numBytesUsed * MEMORY_UNDERESTIMATION_FACTOR;
    }

    /**
     * Detailed information about objects used by this Tile.
     */
    getUsageStatistics(): TileResourceUsageInfo {
        const renderInfo: TileResourceUsageInfo = {
            estimatedMemoryUsage: this.memoryUsage,
            numVertices: this.m_numVertices,
            numColors: ColorCache.instance.size,
            numObjects: this.objects.length,
            numGeometries:
                this.m_decodedTile !== undefined ? this.m_decodedTile.geometries.length : 0,
            numMaterials: this.getMaterialsCount()
        };
        return renderInfo;
    }

    /**
     * Gets the list of developer-defined [[TextElement]] in this `Tile`. This list is always
     * rendered first.
     */
    get userTextElements(): TextElement[] {
        return this.m_userTextElements;
    }

    /**
     * Adds a developer-defined [[TextElement]] to this `Tile`. The [[TextElement]] is always
     * visible, if it's in the map's currently visible area.
     *
     * @param textElement The Text element to add.
     */
    addUserTextElement(textElement: TextElement) {
        this.m_userTextElements.push(textElement);
        this.textElementsChanged = true;
    }

    /**
     * Removes a developer-defined [[TextElement]] from this `Tile`.
     *
     * @param textElement A developer-defined TextElement to remove.
     * @returns `true` if the element has been removed successfully; `false` otherwise.
     */
    removeUserTextElement(textElement: TextElement): boolean {
        const foundIndex = this.m_userTextElements.indexOf(textElement);
        if (foundIndex >= 0) {
            this.m_userTextElements.splice(foundIndex, 1);
            this.textElementsChanged = true;
            return true;
        }
        return false;
    }

    /**
     * Adds a [[TextElement]] to this `Tile`, which is added to the visible set of
     * [[TextElement]]s based on the capacity and visibility. The [[TextElement]]'s priority
     * controls if or when it becomes visible.
     *
     * To ensure that a TextElement is visible, use a high value for its priority, such as
     * `Number.MAX_SAFE_INTEGER`. Since the number of visible TextElements is limited by the
     * screen space, not all TextElements are visible at all times.
     *
     * @param textElement The TextElement to add.
     */
    addTextElement(textElement: TextElement) {
        this.textElementGroups.add(textElement);
        this.textElementsChanged = true;
    }

    /**
     * Removes a [[TextElement]] from this `Tile`. For the element to be removed successfully, the
     * priority of the [[TextElement]] has to be equal to its priority when it was added.
     *
     * @param textElement The TextElement to remove.
     * @returns `true` if the TextElement has been removed successfully; `false` otherwise.
     */
    removeTextElement(textElement: TextElement): boolean {
        if (this.textElementGroups.remove(textElement)) {
            this.textElementsChanged = true;
            return true;
        }
        return false;
    }

    /**
     * Gets the current [[GroupedPriorityList]] which contains a list of all [[TextElement]]s to be
     * selected and placed for rendering.
     */
    get textElementGroups(): GroupedPriorityList<TextElement> {
        return this.m_textElementGroups;
    }

    /**
     * Gets the current modification state for the list of [[TextElement]]s in the `Tile`. If the
     * value is `true` the TextElement is placed for rendering during the next frame.
     */
    get textElementsChanged(): boolean {
        return this.m_textElementsChanged;
    }

    set textElementsChanged(changed: boolean) {
        this.m_textElementsChanged = changed;
    }

    /**
     * Called by [[VisibleTileSet]] to mark that [[Tile]] is visible and it should prepare geometry.
     */
    prepareForRender() {
        if (!this.m_decodedTile || this.m_disposed) {
            return;
        }
        const decodedTile = this.m_decodedTile;

        if (decodedTile.tileInfo !== undefined) {
            this.roadIntersectionData = this.dataSource.mapView.pickHandler.registerTile(this);
        }

        this.m_decodedTile = undefined;

        setTimeout(() => {
            const stats = this.mapView.statistics;
            let now = 0;
            if (stats.enabled) {
                now = PerformanceTimer.now();
            }

            this.createGeometries(decodedTile);

            if (stats.enabled) {
                stats.getTimer("geometryCreation").setValue(PerformanceTimer.now() - now);
            }

            this.dataSource.requestUpdate();
        }, 0);
    }

    /**
     * Called before [[MapView]] starts rendering this `Tile`.
     *
     * @param zoomLevel The current zoom level.
     * @returns Returns `true` if this `Tile` should be rendered.
     */
    willRender(_zoomLevel: number): boolean {
        return true;
    }

    /**
     * Called after [[MapView]] has rendered this `Tile`.
     */
    didRender(): void {
        // to be overriden by subclasses
    }

    /**
     * Called after the `Tile` has been decoded.
     *
     * @param decodedTile The [[DecodedTile]].
     */
    createGeometries(decodedTile: DecodedTile) {
        this.clear();
        this.preparePois(decodedTile);
        this.createTextElements(decodedTile);
        this.createObjects(decodedTile, this.objects);
        this.countVertices();
    }

    /**
     * Gets the decoded tile; it is removed after geometry handling.
     */
    get decodedTile(): DecodedTile | undefined {
        return this.m_decodedTile;
    }

    /**
     * Called by [[TileLoader]] when data for geometry is available.
     *
     * @param decodedTile
     */
    setDecodedTile(decodedTile: DecodedTile) {
        this.m_decodedTile = decodedTile;
        this.invalidateUsageInfoCache();

        const dataSource = this.dataSource;
        const stats = dataSource.mapView.statistics;
        if (stats.enabled) {
            stats.getTimer("decoding").setValue(decodedTile.decodeTime);
        }
    }

    /**
     * Called when the default implementation of `dispose()` needs
     * to free the geometry of a `Tile` object.
     *
     * @param object The object that references the geometry.
     * @returns `true` if the geometry can be disposed.
     */
    // tslint:disable-next-line:no-unused-variable
    shouldDisposeObjectGeometry(object: TileObject): boolean {
        return true;
    }

    /**
     * Called when the default implementation of `dispose()` needs
     * to free a `Tile` object's material.
     *
     * @param object The object referencing the geometry.
     * @returns `true` if the material can be disposed.
     */
    // tslint:disable-next-line:no-unused-variable
    shouldDisposeObjectMaterial(object: TileObject): boolean {
        return true;
    }

    /**
     * Returns `true` if this `Tile` has been disposed.
     */
    get disposed(): boolean {
        return this.m_disposed;
    }

    /**
     * MapView checks if this `Tile` is ready to be rendered while culling.
     *
     * By default, MapView checks if the [[objects]] list is not empty. However, you can override
     * this check by manually setting this property.
     */
    get hasGeometry(): boolean {
        if (this.m_forceHasGeometry === undefined) {
            return this.objects.length !== 0;
        } else {
            return this.m_forceHasGeometry;
        }
    }

    /**
     * Overrides the default value for [[hasGeometry]].
     *
     * @param value A new value for the [[hasGeometry]] flag.
     */
    forceHasGeometry(value: boolean) {
        this.m_forceHasGeometry = value;
    }

    /**
     * Gets the [[ITileLoader]] that manages this tile.
     */
    get tileLoader(): ITileLoader | undefined {
        return this.m_tileLoader;
    }

    /**
     * Sets the [[ITileLoader]] to manage this tile.
     *
     * @param tileLoader A [[ITileLoader]] instance to manage the loading process for this tile.
     */
    set tileLoader(tileLoader: ITileLoader | undefined) {
        this.m_tileLoader = tileLoader;
    }

    /**
     * Forces the update of this `Tile` geometry.
     */
    reload() {
        this.dataSource.updateTile(this);
    }

    /**
     * Frees the rendering resources allocated by this `Tile`.
     *
     * The default implementation of this method frees the geometries and
     * the materials for all the reachable objects.
     */
    clear() {
        const disposeObject = (object: TileObject & DisposableObject) => {
            if (object.geometry !== undefined && this.shouldDisposeObjectGeometry(object)) {
                object.geometry.dispose();
            }

            if (object.material !== undefined && this.shouldDisposeObjectMaterial(object)) {
                if (object.material instanceof Array) {
                    object.material.forEach(material => material.dispose());
                } else {
                    object.material.dispose();
                }
            }
        };

        this.objects.forEach((rootObject: TileObject & DisposableObject) => {
            rootObject.traverse((object: TileObject & DisposableObject) => {
                disposeObject(object);
            });

            disposeObject(rootObject);
        });

        this.objects.length = 0;
        if (this.m_preparedTextPaths) {
            this.m_preparedTextPaths = [];
        }

        this.placedTextElements.clear();
        this.textElementGroups.clear();
        this.userTextElements.length = 0;
        this.invalidateUsageInfoCache();
    }

    /**
     * Disposes this `Tile`, freeing all geometries and materials for the reachable objects.
     */
    dispose() {
        if (this.m_disposed) {
            return;
        }
        if (this.m_tileLoader) {
            this.m_tileLoader.dispose();
            this.m_tileLoader = undefined;
        }
        this.clear();
        this.userTextElements.length = 0;
        this.m_disposed = true;
    }

    /**
     * Gets the prepared text geometries that are optimized for display.
     */
    get preparedTextPaths(): TextPathGeometry[] {
        return this.m_preparedTextPaths;
    }

    /**
     * Splits the text paths that contain sharp corners.
     *
     * @param textPathGeometries The original path geometries that may have defects.
     */
    prepareTextPaths(textPathGeometries: TextPathGeometry[]): TextPathGeometry[] {
        const processedPaths = new Array<TextPathGeometry>();

        const MAX_CORNER_ANGLE = Math.PI / 8;

        const newPaths = textPathGeometries.slice();

        // maximum reuse of variables to reduce allocations
        const p0 = new THREE.Vector2();
        const p1 = new THREE.Vector2();
        const previousTangent = new THREE.Vector2();

        while (newPaths.length > 0) {
            const textPath = newPaths.pop();

            if (textPath === undefined) {
                break;
            }

            let splitIndex = -1;

            for (let i = 0; i < textPath.path.length - 2; i += 2) {
                p0.set(textPath.path[i], textPath.path[i + 1]);
                p1.set(textPath.path[i + 2], textPath.path[i + 3]);
                const tangent = p1.sub(p0).normalize();

                if (i > 0) {
                    const theta = Math.atan2(
                        previousTangent.x * tangent.y - tangent.x * previousTangent.y,
                        tangent.dot(previousTangent)
                    );

                    if (Math.abs(theta) > MAX_CORNER_ANGLE) {
                        splitIndex = i;
                        break;
                    }
                }
                previousTangent.set(tangent.x, tangent.y);
            }

            if (splitIndex > 0) {
                // split off the valid first path points with a clone of the path
                const firstTextPath = {
                    path: textPath.path.slice(0, splitIndex + 2),
                    text: textPath.text,
                    // Used for placement priorities only, can be kept although it could also be
                    // recomputed
                    pathLengthSqr: textPath.pathLengthSqr,
                    technique: textPath.technique,
                    featureId: textPath.featureId
                };

                processedPaths.push(firstTextPath);

                // setup a second part with the rest of the path points and process again
                const secondTextPath = {
                    path: textPath.path.slice(splitIndex),
                    text: textPath.text,
                    // Used for placement priorities only, can be kept although it could also be
                    // recomputed
                    pathLengthSqr: textPath.pathLengthSqr,
                    technique: textPath.technique,
                    featureId: textPath.featureId
                };

                newPaths.push(secondTextPath);
            } else {
                processedPaths.push(textPath);
            }
        }
        return processedPaths;
    }

    /**
     * Creates [[TextElement]] objects from the decoded tile and list of materials specified. The
     * priorities of the [[TextElement]]s are updated to simplify label placement.
     *
     * @param decodedTile The [[DecodedTile]].
     */
    createTextElements(decodedTile: DecodedTile) {
        const colorMap = new Map<number, THREE.Color>();

        // gather the sum of [[TextElement]]s (upper boundary), to compute the priority, such that
        // the text elements that come first get the highest priority, so they get placed first.
        let numTextElements = 0;
        let numTextElementsCreated = 0;

        if (decodedTile.textPathGeometries !== undefined) {
            numTextElements += decodedTile.textPathGeometries.length;
        }
        if (decodedTile.textGeometries !== undefined) {
            numTextElements += decodedTile.textGeometries.length;
        }

        const displayZoomLevel = this.mapView.zoomLevel;
        if (decodedTile.textPathGeometries !== undefined) {
            this.m_preparedTextPaths = this.prepareTextPaths(decodedTile.textPathGeometries);

            // Compute maximum street length (squared). Longer streets should be labelled first,
            // they have a higher chance of being placed in case the number of text elements is
            // limited.
            let maxPathLengthSqr = 0;
            for (const textPath of this.preparedTextPaths) {
                const technique = decodedTile.techniques[textPath.technique];
                if (technique.name !== "text") {
                    continue;
                }
                if (textPath.pathLengthSqr > maxPathLengthSqr) {
                    maxPathLengthSqr = textPath.pathLengthSqr;
                }
            }

            for (const textPath of this.preparedTextPaths) {
                const technique = decodedTile.techniques[textPath.technique];
                if (technique.name !== "text") {
                    continue;
                }
                const color = getPropertyValue(technique.color, displayZoomLevel);
                if (color !== undefined) {
                    colorMap.set(textPath.technique, ColorCache.instance.getColor(color));
                }
                const path: THREE.Vector2[] = [];
                for (let i = 0; i < textPath.path.length; i += 2) {
                    path.push(new THREE.Vector2(textPath.path[i], textPath.path[i + 1]));
                }

                // Make sorting stable and make pathLengthSqr a differentiator for placement.
                const priority =
                    getOptionValue(getPropertyValue(technique.priority, displayZoomLevel), 0) +
                    (SORT_WEIGHT_SEQUENCE * (numTextElements - numTextElementsCreated)) /
                        numTextElements +
                    (maxPathLengthSqr > 0
                        ? (SORT_WEIGHT_PATH_LENGTH * textPath.pathLengthSqr) / maxPathLengthSqr
                        : 0);

                const textElement = new TextElement(
                    textPath.text,
                    path,
                    priority,
                    getOptionValue(getPropertyValue(technique.scale, displayZoomLevel), 1.0),
                    technique.xOffset !== undefined ? technique.xOffset : 0.0,
                    technique.yOffset !== undefined ? technique.yOffset : 0.0,
                    textPath.featureId,
                    technique.style,
                    technique.allCaps,
                    technique.smallCaps,
                    technique.oblique,
                    technique.bold,
                    technique.tracking,
                    getPropertyValue(technique.fadeNear, displayZoomLevel),
                    getPropertyValue(technique.fadeFar, displayZoomLevel)
                );
                textElement.color = colorMap.get(textPath.technique);
                textElement.minZoomLevel =
                    technique.minZoomLevel !== undefined
                        ? technique.minZoomLevel
                        : this.mapView.minZoomLevel;
                textElement.maxZoomLevel =
                    technique.maxZoomLevel !== undefined
                        ? technique.maxZoomLevel
                        : this.mapView.maxZoomLevel;
                textElement.distanceScale =
                    technique.distanceScale !== undefined
                        ? technique.distanceScale
                        : DEFAULT_TEXT_DISTANCE_SCALE;
                textElement.mayOverlap = technique.mayOverlap === true;
                textElement.reserveSpace = technique.reserveSpace !== false;

                if (
                    technique.hAlignment !== undefined &&
                    (technique.hAlignment === TextHorizontalAlignmentStrings.Left ||
                        technique.hAlignment === TextHorizontalAlignmentStrings.Center ||
                        technique.hAlignment === TextHorizontalAlignmentStrings.Right)
                ) {
                    textElement.horizontalAlignment = TextHorizontalAlignment[technique.hAlignment];
                }
                if (
                    technique.vAlignment !== undefined &&
                    (technique.vAlignment === TextVerticalAlignmentStrings.Above ||
                        technique.vAlignment === TextVerticalAlignmentStrings.Center ||
                        technique.vAlignment === TextVerticalAlignmentStrings.Below)
                ) {
                    textElement.verticalAlignment = TextVerticalAlignment[technique.vAlignment];
                }

                this.addTextElement(textElement);
                numTextElementsCreated++;
            }
        }

        if (decodedTile.textGeometries !== undefined) {
            for (const text of decodedTile.textGeometries) {
                if (text.technique === undefined || text.stringCatalog === undefined) {
                    continue;
                }

                const technique = decodedTile.techniques[text.technique];

                if (technique.name !== "text") {
                    continue;
                }

                const color = getPropertyValue(technique.color, displayZoomLevel);
                if (color !== undefined) {
                    colorMap.set(text.technique, ColorCache.instance.getColor(color));
                }
                const positions = new THREE.BufferAttribute(
                    new Float32Array(text.positions.buffer),
                    text.positions.itemCount
                );

                const numPositions = positions.count;
                if (numPositions < 1) {
                    continue;
                }

                // Keep TextElements sorted. The builtin sorting method is not stable, and a stable
                // sorting should reduce flicker of labels.
                const priority =
                    getOptionValue(getPropertyValue(technique.priority, displayZoomLevel), 0) +
                    (SORT_WEIGHT_SEQUENCE * (numTextElements - numTextElementsCreated)) /
                        numTextElements;
                const singleElementPriorityFactor = SORT_WEIGHT_SEQUENCE / numPositions;

                for (let i = 0; i < numPositions; ++i) {
                    const x = positions.getX(i);
                    const y = positions.getY(i);
                    const label = text.stringCatalog[text.texts[i]];
                    if (label === undefined) {
                        // skip missing labels
                        continue;
                    }

                    const singleElementPriority =
                        priority +
                        (singleElementPriorityFactor * (numPositions - i)) / numPositions;

                    const textElement = new TextElement(
                        label!,
                        new THREE.Vector2(x, y),
                        singleElementPriority,
                        getOptionValue(getPropertyValue(technique.scale, displayZoomLevel), 1.0),
                        technique.xOffset || 0.0,
                        technique.yOffset || 0.0,
                        text.featureId,
                        technique.style,
                        technique.allCaps,
                        technique.smallCaps,
                        technique.oblique,
                        technique.bold,
                        technique.tracking
                    );

                    textElement.color = colorMap.get(text.technique);
                    textElement.minZoomLevel =
                        technique.minZoomLevel !== undefined
                            ? technique.minZoomLevel
                            : this.mapView.minZoomLevel;
                    textElement.maxZoomLevel =
                        technique.maxZoomLevel !== undefined
                            ? technique.maxZoomLevel
                            : this.mapView.maxZoomLevel;
                    textElement.mayOverlap = technique.mayOverlap === true;
                    textElement.reserveSpace = technique.reserveSpace !== false;

                    textElement.fadeNear = getPropertyValue(technique.fadeNear, displayZoomLevel);
                    textElement.fadeFar = getPropertyValue(technique.fadeFar, displayZoomLevel);

                    if (
                        technique.hAlignment !== undefined &&
                        (technique.hAlignment === TextHorizontalAlignmentStrings.Left ||
                            technique.hAlignment === TextHorizontalAlignmentStrings.Center ||
                            technique.hAlignment === TextHorizontalAlignmentStrings.Right)
                    ) {
                        textElement.horizontalAlignment =
                            TextHorizontalAlignment[technique.hAlignment];
                    }
                    if (
                        technique.vAlignment !== undefined &&
                        (technique.vAlignment === TextVerticalAlignmentStrings.Above ||
                            technique.vAlignment === TextVerticalAlignmentStrings.Center ||
                            technique.vAlignment === TextVerticalAlignmentStrings.Below)
                    ) {
                        textElement.verticalAlignment = TextVerticalAlignment[technique.vAlignment];
                    }

                    this.addTextElement(textElement);
                    numTextElementsCreated++;
                }
            }
        }
    }

    /**
     * Adds a THREE object to the root of the tile. Sets the owning tiles datasource.name and the
     * tileKey in the `userData` property of the object, such that the tile it belongs to can be
     * identified during picking.
     *
     * @param object The object to add to the root of the tile.
     */
    registerTileObject(object: THREE.Object3D) {
        const userData = object.userData || {};
        userData.tileKey = this.tileKey;
        userData.dataSource = this.dataSource.name;
    }

    /**
     * Creates `Tile` objects from the decoded tile and list of materials specified.
     *
     * @param decodedTile The [[DecodedTile]].
     * @param objects The current list of tile objects.
     */
    createObjects(decodedTile: DecodedTile, objects: TileObject[]) {
        const materials: THREE.Material[] = [];
        const displayZoomLevel = this.mapView.zoomLevel;
        for (const srcGeometry of decodedTile.geometries) {
            const groups = srcGeometry.groups;
            const groupCount = groups.length;

            for (let groupIndex = 0; groupIndex < groupCount; ) {
                const group = groups[groupIndex++];
                const start = group.start;
                const techniqueIndex = group.technique;
                const technique = decodedTile.techniques[techniqueIndex];

                let count = group.count;

                // compress consecutive groups
                for (
                    ;
                    groupIndex < groupCount && groups[groupIndex].technique === techniqueIndex;
                    ++groupIndex
                ) {
                    if (start + count !== groups[groupIndex].start) {
                        break;
                    }

                    count += groups[groupIndex].count;
                }

                const ObjectCtor = getObjectConstructor(technique);

                if (ObjectCtor === undefined) {
                    continue;
                }

                let material: THREE.Material | undefined = materials[techniqueIndex];

                if (material === undefined) {
                    material = createMaterial({
                        technique: decodedTile.techniques[techniqueIndex],
                        level: displayZoomLevel,
                        fog: this.mapView.scene.fog !== null
                    });
                    if (material === undefined) {
                        continue;
                    }
                    materials[techniqueIndex] = material;
                }

                const bufferGeometry = new THREE.BufferGeometry();

                srcGeometry.vertexAttributes.forEach(vertexAttribute => {
                    const buffer = getBufferAttribute(vertexAttribute);
                    bufferGeometry.addAttribute(vertexAttribute.name, buffer);
                });

                if (srcGeometry.interleavedVertexAttributes !== undefined) {
                    srcGeometry.interleavedVertexAttributes.forEach(attr => {
                        const ArrayCtor = getArrayConstructor(attr.type);
                        const buffer = new THREE.InterleavedBuffer(
                            new ArrayCtor(attr.buffer),
                            attr.stride
                        );
                        attr.attributes.forEach(interleavedAttr => {
                            const attribute = new THREE.InterleavedBufferAttribute(
                                buffer,
                                interleavedAttr.itemSize,
                                interleavedAttr.offset,
                                false
                            );
                            bufferGeometry.addAttribute(interleavedAttr.name, attribute);
                        });
                    });
                }

                if (srcGeometry.index) {
                    bufferGeometry.setIndex(getBufferAttribute(srcGeometry.index));
                }

                if (!bufferGeometry.getAttribute("normal") && isStandardTechnique(technique)) {
                    bufferGeometry.computeVertexNormals();
                }

                bufferGeometry.addGroup(start, count);

                if (technique.name === "solid-line" || technique.name === "dashed-line") {
                    const lineMaterial = material as THREE.RawShaderMaterial;
                    lineMaterial.uniforms.opacity.value = material.opacity;

                    if (technique.clipping !== false) {
                        const tileSize = lineMaterial.uniforms.tileSize;
                        const size = new THREE.Vector3();
                        this.boundingBox.getSize(size);
                        tileSize.value.x = size.x;
                        tileSize.value.y = size.y;
                        lineMaterial.defines.TILE_CLIP = 1;
                    }
                }

                // Add polygon offset to the extruded buildings and to the fill area to avoid depth
                // problems when rendering edges.
                const isExtruded: boolean =
                    technique.name === "extruded-polygon" && srcGeometry.edgeIndex !== undefined;
                const isFilled: boolean =
                    technique.name === "fill" && srcGeometry.outlineIndicesAttributes !== undefined;
                if (isExtruded || isFilled) {
                    material.polygonOffset = true;
                    material.polygonOffsetFactor = 0.25;
                    material.polygonOffsetUnits = 0.1;
                }

                const object = new ObjectCtor(bufferGeometry, material);

                object.frustumCulled = false;

                if (technique.renderOrder !== undefined) {
                    object.renderOrder = technique.renderOrder;
                } else {
                    if (technique._renderOrderAuto === undefined) {
                        throw new Error("Technique has no renderOrderAuto");
                    }
                    object.renderOrder = technique._renderOrderAuto;
                }

                if (group.renderOrderOffset !== undefined) {
                    object.renderOrder += group.renderOrderOffset;
                }

                if (srcGeometry.uuid !== undefined) {
                    object.userData.geometryId = srcGeometry.uuid;
                }

                // Lines renderOrder fix: Render them as transparent objects, but make sure they end
                // up in the opaque rendering queue (by disabling transparency onAfterRender, and
                // enabling it onBeforeRender).
                if (technique.name === "solid-line" || technique.name === "dashed-line") {
                    const fadingParams = this.getFadingParams(technique as SolidLineTechnique);
                    FadingFeature.addRenderHelper(
                        object,
                        fadingParams.fadeNear,
                        fadingParams.fadeFar,
                        true,
                        false,
                        (renderer, mat) => {
                            const lineMaterial = mat as SolidLineMaterial;

                            // Modify the lineWidth every frame for "Pixel-wide" lines.
                            const metricUnits = getAttributeValue(
                                technique.metricUnit,
                                this.tileKey.level
                            );
                            if (metricUnits === "Pixel") {
                                const pixelToWorld =
                                    renderer.getPixelRatio() * this.mapView.pixelToWorld * 0.5;
                                const lineWidth = getAttributeValue(
                                    technique.lineWidth,
                                    displayZoomLevel
                                );
                                lineMaterial.lineWidth =
                                    (lineWidth !== undefined
                                        ? (lineWidth as number)
                                        : SolidLineMaterial.DEFAULT_WIDTH) * pixelToWorld;

                                // Do the same for dashSize and gapSize for dashed lines.
                                if (technique.name === "dashed-line") {
                                    const dashedLineMaterial = lineMaterial as DashedLineMaterial;

                                    const dashSize = getAttributeValue(
                                        technique.dashSize,
                                        displayZoomLevel
                                    );
                                    dashedLineMaterial.dashSize =
                                        (dashSize !== undefined
                                            ? (dashSize as number)
                                            : DashedLineMaterial.DEFAULT_DASH_SIZE) * pixelToWorld;

                                    const gapSize = getAttributeValue(
                                        technique.gapSize,
                                        displayZoomLevel
                                    );
                                    dashedLineMaterial.gapSize =
                                        (gapSize !== undefined
                                            ? (gapSize as number)
                                            : DashedLineMaterial.DEFAULT_GAP_SIZE) * pixelToWorld;
                                }
                            }
                        }
                    );
                }

                if (technique.name === "extruded-line") {
                    // extruded lines are normal meshes, and need transparency only when fading
                    // is defined.
                    if (technique.fadeFar !== undefined && technique.fadeFar >= 0) {
                        const fadingParams = this.getFadingParams(
                            technique as StandardExtrudedLineTechnique
                        );
                        FadingFeature.addRenderHelper(
                            object,
                            fadingParams.fadeNear,
                            fadingParams.fadeFar,
                            true,
                            true
                        );
                    }
                }

                this.addFeatureData(srcGeometry, technique, object);

                if (isExtruded || technique.name === "fill") {
                    const fillTechnique = technique as FillTechnique;

                    // filled polygons are normal meshes, and need transparency only when fading is
                    // defined.
                    if (technique.fadeFar !== undefined && technique.fadeFar >= 0) {
                        const fadingParams = this.getFadingParams(fillTechnique);

                        FadingFeature.addRenderHelper(
                            object,
                            fadingParams.fadeNear,
                            fadingParams.fadeFar,
                            true,
                            true
                        );
                    }
                }

                const renderDepthPrePass =
                    technique.name === "extruded-polygon" && isRenderDepthPrePassEnabled(technique);

                if (renderDepthPrePass) {
                    const depthPassMesh = createDepthPrePassMesh(object as THREE.Mesh);
                    objects.push(depthPassMesh);

                    applyDepthBasedPolygonOffset(
                        DEFAULT_DEPTH_BASED_POLYGON_OFFSET_MULTIPLIER,
                        depthPassMesh,
                        object as THREE.Mesh
                    );
                }

                this.registerTileObject(object);

                objects.push(object);

                // Add the extruded building edges as a separate geometry.
                if (technique.name === "extruded-polygon" && srcGeometry.edgeIndex !== undefined) {
                    const edgeGeometry = new THREE.BufferGeometry();
                    edgeGeometry.addAttribute("position", bufferGeometry.getAttribute("position"));
                    edgeGeometry.addAttribute("color", bufferGeometry.getAttribute("color"));
                    edgeGeometry.setIndex(getBufferAttribute(srcGeometry.edgeIndex));

                    // Read the uniforms from the technique values (and apply the default values).
                    const extrudedPolygonTechnique = technique as ExtrudedPolygonTechnique;

                    const fadingParams = this.getPolygonFadingParams(extrudedPolygonTechnique);

                    // Configure the edge material based on the theme values.
                    const materialParams: EdgeMaterialParameters = {
                        color: fadingParams.color,
                        colorMix: fadingParams.colorMix,
                        fadeNear: fadingParams.lineFadeNear,
                        fadeFar: fadingParams.lineFadeFar
                    };
                    const edgeMaterial = new EdgeMaterial(materialParams);
                    const edgeObj = new THREE.LineSegments(edgeGeometry, edgeMaterial);

                    // Set the correct render order (based on transparency).
                    edgeObj.renderOrder =
                        edgeMaterial.transparent && !renderDepthPrePass
                            ? -1
                            : object.renderOrder + 0.1;

                    FadingFeature.addRenderHelper(
                        edgeObj,
                        fadingParams.lineFadeNear,
                        fadingParams.lineFadeFar,
                        true,
                        false
                    );

                    this.registerTileObject(edgeObj);
                    objects.push(edgeObj);
                }

                // polygon outline
                if (isFilled && srcGeometry.outlineIndicesAttributes !== undefined) {
                    // iterate through all the arrays inside the outlineIndicesAttributes for each
                    // of them, create an object and add it to objects
                    for (const indices of srcGeometry.outlineIndicesAttributes) {
                        const outlineGeometry = new THREE.BufferGeometry();
                        outlineGeometry.addAttribute(
                            "position",
                            bufferGeometry.getAttribute("position")
                        );
                        if (indices !== undefined) {
                            outlineGeometry.setIndex(getBufferAttribute(indices));
                        }

                        const fillTechnique = technique as FillTechnique;

                        const fadingParams = this.getPolygonFadingParams(fillTechnique);

                        // Configure the edge material based on the theme values.
                        const materialParams: EdgeMaterialParameters = {
                            color: fadingParams.color,
                            colorMix: fadingParams.colorMix,
                            fadeNear: fadingParams.lineFadeNear,
                            fadeFar: fadingParams.lineFadeFar
                        };
                        const outlineMaterial = new EdgeMaterial(materialParams);
                        const outlineObj = new THREE.LineSegments(outlineGeometry, outlineMaterial);
                        outlineObj.renderOrder = object.renderOrder + 0.1;

                        FadingFeature.addRenderHelper(
                            outlineObj,
                            fadingParams.lineFadeNear,
                            fadingParams.lineFadeFar,
                            true,
                            false
                        );

                        this.registerTileObject(outlineObj);
                        objects.push(outlineObj);
                    }
                }
            }
        }
    }

    /**
     * Invalidates resource usage data.
     */
    invalidateUsageInfoCache(): void {
        this.m_numVertices = 0;
        this.m_memoryUsage = undefined;
    }

    /**
     * Counts the number of vertices in a tile.
     */
    countVertices(): void {
        this.objects.filter(object => object instanceof THREE.Mesh).forEach(object => {
            const mesh = object as THREE.Mesh;
            if (mesh.geometry instanceof THREE.BufferGeometry) {
                if (mesh.geometry.index !== undefined && mesh.geometry.index !== null) {
                    this.m_numVertices += mesh.geometry.index.count;
                } else {
                    this.m_numVertices += mesh.geometry.getAttribute("position").count / 3;
                }
            }
            if (mesh.geometry instanceof THREE.Geometry) {
                this.m_numVertices = mesh.geometry.vertices.length;
            }
        });
    }

    /**
     * Missing Typedoc
     */
    protected preparePois(decodedTile: DecodedTile) {
        if (decodedTile.poiGeometries !== undefined) {
            this.mapView.poiManager.addPois(this, decodedTile);
        }
    }

    private getMaterialsCount() {
        let num = 0;
        this.objects.forEach((rootObject: TileObject & DisposableObject) => {
            if (rootObject.material) {
                if (Array.isArray(rootObject.material)) {
                    num += rootObject.material.length;
                } else {
                    num += 1;
                }
            }
        });
        return num;
    }

    private addFeatureData(srcGeometry: Geometry, technique: Technique, object: THREE.Object3D) {
        // Pass the feature data on to the object, so it can be used in picking
        // MapView.intersectMapObjects().
        // Do not pass the feature data if the technique is a dashed-line or a solid-line, because
        // the line picking functionality for the lines is not object based, but tile based.
        if (
            srcGeometry.featureIds !== undefined &&
            srcGeometry.featureIds.length > 0 &&
            technique.name !== "solid-line" &&
            technique.name !== "dashed-line"
        ) {
            const featureData: TileFeatureData = {
                geometryType: srcGeometry.type,
                ids: srcGeometry.featureIds,
                starts: srcGeometry.featureStarts
            };
            object.userData.feature = featureData;

            if (srcGeometry.objInfos !== undefined) {
                object.userData.feature.objInfos = srcGeometry.objInfos;
            }
        }
    }

    /**
     * Gets the fading parameters for several kinds of objects.
     */
    private getFadingParams(
        technique: FillTechnique | SolidLineTechnique | StandardExtrudedLineTechnique
    ): FadingParameters {
        const displayZoomLevel = this.mapView.zoomLevel;
        const fadeNear =
            technique.fadeNear !== undefined
                ? getPropertyValue(technique.fadeNear, displayZoomLevel)
                : FadingFeature.DEFAULT_FADE_NEAR;
        const fadeFar =
            technique.fadeFar !== undefined
                ? getPropertyValue(technique.fadeFar, displayZoomLevel)
                : FadingFeature.DEFAULT_FADE_FAR;
        return {
            fadeNear,
            fadeFar
        };
    }

    /**
     * Gets the fading parameters for several kinds of objects.
     */
    private getPolygonFadingParams(
        technique: FillTechnique | ExtrudedPolygonTechnique
    ): PolygonFadingParameters {
        let color: string | number = EdgeMaterial.DEFAULT_COLOR;
        let colorMix = EdgeMaterial.DEFAULT_COLOR_MIX;

        if (technique.lineColor !== undefined) {
            color = technique.lineColor;
            if (isExtrudedPolygonTechnique(technique)) {
                const extrudedPolygonTechnique = technique as ExtrudedPolygonTechnique;
                colorMix =
                    extrudedPolygonTechnique.lineColorMix !== undefined
                        ? extrudedPolygonTechnique.lineColorMix
                        : EdgeMaterial.DEFAULT_COLOR_MIX;
            }
        }
        const displayZoomLevel = this.mapView.zoomLevel;

        const fadeNear =
            technique.fadeNear !== undefined
                ? getPropertyValue(technique.fadeNear, displayZoomLevel)
                : FadingFeature.DEFAULT_FADE_NEAR;
        const fadeFar =
            technique.fadeFar !== undefined
                ? getPropertyValue(technique.fadeFar, displayZoomLevel)
                : FadingFeature.DEFAULT_FADE_FAR;

        const lineFadeNear =
            technique.lineFadeNear !== undefined
                ? getPropertyValue(technique.lineFadeNear, displayZoomLevel)
                : fadeNear;
        const lineFadeFar =
            technique.lineFadeFar !== undefined
                ? getPropertyValue(technique.lineFadeFar, displayZoomLevel)
                : fadeFar;

        return {
            color,
            colorMix,
            fadeNear,
            fadeFar,
            lineFadeNear,
            lineFadeFar
        };
    }
}
