name: Docs

env:
    GECKODRIVER_SKIP_DOWNLOAD: true
    CHROMEDRIVER_SKIP_DOWNLOAD: true

on:
    workflow_dispatch

jobs:
    docs:
        name: Generate Docs
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v1
        - uses: actions/setup-node@v2-beta
          with:
            node-version: '12'
        - name: Install dependencies
          run: yarn --frozen-lockfile
        - name: Generate docs
          run: yarn docs
        - name: Save API metadata
          uses: actions/upload-artifact@master
          with:
            name: harp-api-metadata
            path: input
        - name: Save API reference
          uses: actions/upload-artifact@master
          with:
            name: harp-api-reference
            path: markdown
